#### 1. Create a class Employee and then do the following
* Create a data member to count the number of Employees
* Create a constructor to initialize name, family, salary, department
* Create a function to average salary
* Create a Fulltime Employee class and it should inherit the properties of Employee class
* Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [20]:
class Employee:
#     class valriable to count total number of employees
    employee_count = 0
    
    def __init__(self,name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        
#         increment count by 1 on each object creation
        Employee.employee_count += 1
    @staticmethod
    def average_salary(employee_list):
        if len(employee_list): 
            return 
        total_salary = sum(emp.salary for emp in employee_list)
        return total_salary / len(employee_list)

In [21]:
class FullTimeEmployee(Employee):
    def __init__(self,name,family,salary,department,bonus):
        super().__init__(name,family,salary,department)
        self.bonus = bonus
    
    def total_compensation(self):
        return self.salary + self.bonus

In [22]:
emp1 = Employee("Admin ","Admin ",100000,"admin")
f_emp1 = FullTimeEmployee("hemanth kumar","Chereddy",60000,"Developer",20000)
f_emp2 = FullTimeEmployee("Naveen","Indluru",63232,"Developer",10000)
f_emp3 = FullTimeEmployee("yamini","Eddala",24278,"Developer",40000)

In [23]:
emp1.employee_count

4

In [24]:
print(f"Total compensation for {f_emp1.name} : {f_emp1.total_compensation()}")
print(f"Total compensation for {f_emp2.name} : {f_emp2.total_compensation()} ") 
print(f"Total compensation for {f_emp3.name} : {f_emp3.total_compensation()} ")
f_emp_list = [f_emp1,f_emp2,f_emp3]
print("Avenrage salary of full time employees :",emp1.average_salary(f_emp_list)) 

Total compensation for hemanth kumar : 80000
Total compensation for Naveen : 73232 
Total compensation for yamini : 64278 
Avenrage salary of full time employees : None


#### 2. Using NumPy create random vector of size 20 having only float in the range 1-20.
* Then reshape the array to 4 by 5
* Then replace the max in each row by 0 (axis=1)


In [28]:
# import numpy library
import numpy as np

# crate random vector of size 20
random_vector = np.random.uniform(1, 20, size=20)
print(f"random vector of size 20 : {random_vector}")

# Reshape the array (can we any shape : it should match the total size of vector)
reshaped_array = random_vector.reshape(5,4)
print(f"Reshaped array(5,4) : {reshaped_array}")

# Replace the max in each row by 0
reshaped_array[np.arange(5), np.argmax(reshaped_array, axis=1)] = 0
print(f"Reshaped array after replacing max with 0 : {reshaped_array}")


random vector of size 20 : [12.69246648 14.99459646  4.31960152  3.24090276 19.69133932  3.5909625
  8.53813263  7.56508498  6.77552274  5.94335297 19.50138112 15.73489875
 14.54062952 11.55042215  4.51106502 11.74482551  7.70360414 17.64421877
 19.02047871  3.48828432]
Reshaped array(5,4) : [[12.69246648 14.99459646  4.31960152  3.24090276]
 [19.69133932  3.5909625   8.53813263  7.56508498]
 [ 6.77552274  5.94335297 19.50138112 15.73489875]
 [14.54062952 11.55042215  4.51106502 11.74482551]
 [ 7.70360414 17.64421877 19.02047871  3.48828432]]
Reshaped array after replacing max with 0 : [[12.69246648  0.          4.31960152  3.24090276]
 [ 0.          3.5909625   8.53813263  7.56508498]
 [ 6.77552274  5.94335297  0.         15.73489875]
 [ 0.         11.55042215  4.51106502 11.74482551]
 [ 7.70360414 17.64421877  0.          3.48828432]]
